---
my_cwd:
  path: "/tmp/my_ansible_cwd/"

systemd_units:
  system:
    path: '/etc/systemd/system/'
  user:
    path: '/etc/systemd/user/'
  global:
    path: '/etc/systemd/user/'


grafana_pkg:
  src: 'https://dl.grafana.com/oss/release/grafana-8.4.0.linux-amd64.tar.gz'
  install_pref: '/opt/grafana-8.4.0'
  exec: '/opt/grafana-8.4.0/bin/grafana-server'

grafana_service:
  ExecStart: '/opt/grafana-8.4.0/bin/grafana-server'

grafana_homepath_dir: '/opt/grafana-8.4.0'
grafana_data_dir: '/var/lib/grafana'
grafana_conf_dir: '/opt/grafana-8.4.0/conf'
